### ISSUE TITLE
Resolve Analysis Warnings

### ISSUE THREAD

**Issue by jamescahall** [ConnectSDK/Connect-SDK-iOS#120]
There are 17 warnings that appear during "Analyze".  Some with possible significant implications such as missing super calls and null dereferencing.

Thanks,
James

**Comment by eunikolsky** [comment]
We need to fix compiler and static analyzer warnings for the next release to properly pass the `podspec` validation with the latest CocoaPods release (0.36.0) https://github.com/CocoaPods/CocoaPods/issues/3261#issuecomment-79048822

**Comment by eunikolsky** [comment]
Fixed in https://github.com/ConnectSDK/Connect-SDK-iOS/commit/c5804d5f6ec134d05d8860fa554ba6bb235b3aea and https://github.com/ConnectSDK/Connect-SDK-iOS-Lite/commit/ca704c02e29e0ac4bf9685598552d24153894adc

The `GCDWebServer` library was updated to 3.2.2 that has fixed its warnings (https://github.com/swisspol/GCDWebServer/issues/122).
