### ISSUE TITLE
Upgrade Google cast to v2.6

### ISSUE THREAD

**Issue by iadnan** [ConnectSDK/Connect-SDK-iOS#142]
Upgrade google cast framework to v 2.6 with support for google cast audio

**Comment by iadnan** [comment]
Upgraded to Google cast SDK v2.6 https://github.com/ConnectSDK/Connect-SDK-iOS/commit/3960f10717948853a507ea8103d3b5ba42aac392

**Comment by eunikolsky** [comment]
When I try to launch a web app on Music Flow, the error is returned: "web app launch error: Application was not found", which probably makes sense, since the device doesn't have a display to render a web app. SDK 2.6 has the new [`-[GCKDevice hasCapabilities:]`](https://developers.google.com/cast/docs/reference/ios/interface_g_c_k_device.html#ac9462ff1c1707daa727573b385eb5be3) method, which we can use to adjust the capabilities of a particular `CastService`. ChromeCast has both `kGCKDeviceCapabilityAudioOut` and `kGCKDeviceCapabilityVideoOut`, whereas Music Flow has `kGCKDeviceCapabilityAudioOut` only.

@iadnan, what do you think?

**Comment by iadnan** [comment]
Yes this sounds good to have dynamic capabilities . Also we need to find which other services apart from Chromecast support this. WebOS , DLNA ?

**Comment by iadnan** [comment]
We already have an API to get list of services provided my WebOS TV getServiceListWithSuccess:failure: (ssap://api/getServiceList) . We can utilize this API to get list of capabilities

**Comment by eunikolsky** [comment]
Yes, we know that the DLNA spec has support for that. However, I think these Cast capabilities are not "fully dynamic", because they can be set right after a Cast device is discovered. Dynamic capabilities can be implemented later for other services (for DLNA/WebOS you're required to connect first).

I think we should reopen the issue and add the Cast capabilities support.

**Comment by eunikolsky** [comment]
@iadnan, any objections?

**Comment by eunikolsky** [comment]
Turns out it's not that easy to adjust the capabilities with the current setup. Discovery provider has access to the device object, but doesn't create a service directly. And the service creates a device object only when connecting. If we move that before connection (eg, when asked to update capabilities), it should work.

**Comment by iadnan** [comment]
I am not sure If i understand you right . We will get the capabilities only after we connect and not before it. I believe we should update the capabilities after the connection .

**Comment by eunikolsky** [comment]
> We will get the capabilities only after we connect and not before it. 

Yes, this is a limitation for DLNA/WebOS/etc. However, it is possible to get the capabilities of a Cast device at the discovery time. So why not do it?

Practically, the [`GCKDevice` object received in discovery provider](https://github.com/ConnectSDK/Connect-SDK-iOS-Google-Cast/blob/master/CastDiscoveryProvider.m#L88) provides the `-hasCapabilities:` method, which works fine. But we recreate the [`GCKDevice` object later in `CastService`](https://github.com/ConnectSDK/Connect-SDK-iOS-Google-Cast/blob/master/CastService.m#L149) (based on IP and port). First of all, it's currently created only on connect. I tried creating earlier, but that object's `-hasCapabilities:` always returns `NO` (it may be a bug in the SDK). So, to fix that, we need to somehow pass the original `GCKDevice` object from `CastDiscoveryProvider` to `CastService`.

**Comment by eunikolsky** [comment]
Here's some POC code: https://github.com/eunikolsky/Connect-SDK-iOS-Google-Cast/commit/92656527bee9b5c0daa87931034d7d3251971bdc which prints the following:
```
[discovery] Family: can audio? 1, can video? 0
[discovery] Chromecast-Connect-SDK: can audio? 1, can video? 1
[service] Family: can audio? 0, can video? 0
[service] Chromecast-Connect-SDK: can audio? 0, can video? 0
[connected] Family: can audio? 0, can video? 0
```
