### ISSUE TITLE
Unable to Connect to LG music flow speakers using google cast for audio

### ISSUE THREAD

**Issue by iadnan** [ConnectSDK/Connect-SDK-iOS#147]
Unable to connect to music flow speaker via CastService as DLNAService is getting disconnected.

**Comment by iadnan** [comment]
Found the root cause. The AVTransportURL is invalid. There is a '/' missing in the control URL

**Comment by iadnan** [comment]
issue fixed in https://github.com/ConnectSDK/Connect-SDK-iOS-Core/commit/23b68bc9eb55171dd8d2780475e4d5e8772fbad5

**Comment by eunikolsky** [comment]
Found a related issue: subscriptions don't work. Here's the `connectionError` at https://github.com/ConnectSDK/Connect-SDK-iOS-Core/blob/dev/Services/DLNAService.m#L417:
```
Error Domain=NSURLErrorDomain Code=-1004 "Could not connect to the server." UserInfo=0x7fd2e418af50 {NSUnderlyingError=0x7fd2e4192150 "Could not connect to the server.", NSErrorFailingURLStringKey=http://192.168.1.7:2870event/RenderingControl, NSErrorFailingURLKey=http://192.168.1.7:2870event/RenderingControl, _kCFStreamErrorDomainKey=1, _kCFStreamErrorCodeKey=61, NSLocalizedDescription=Could not connect to the server.}
```

The URL is wrong: `http://192.168.1.7:2870event/RenderingControl`. Basically, the URL construction code (`stringWithFormat:@"http://%@:%@%@"`) is duplicated in **six** places! It **must** be cleaned up.

**TODO**: find all such places where this bug is; write tests.

**Comment by iadnan** [comment]
event subscription fix available in https://github.com/ConnectSDK/Connect-SDK-iOS-Core/pull/22

**Comment by eunikolsky** [comment]
@iadnan, thanks! A few things:

1. Checked on the device – the subscriptions work properly now.
2. One URL construction `%@%@` place left in `-getMetaDataDictionary:`. I believe it should use `-serviceURLForPath:` as well. Any reason you didn't do that?
3. The tests names end with `BackSlash`. It should be `Slash` (because URLs use (forward) slashes `/`, not backslashes `\`).
4. The new tests are between helper methods in the source file. They should be placed in a separate subpart (that is, `#pragma mark - `).

I'm going to fix these things.

**Comment by eunikolsky** [comment]
Merged in Full and Lite.
